### ISSUE TITLE
Enabling the extension (PHP 5.5.9 - Ubuntu 14.04.2)

### ISSUE THREAD

**Issue by nebulorum** [NewEraCracker/eaccelerator#1]
I recently migrated to PHP 5.5.9 (as part of an Ubuntu 14.04.2 migration). I followed the procedures I always used to get the eAccelerator on PHP 5.4. Using your 1.1-dev zip, followed the steps all the way to sudo make install. The .so is in the correct place, but the extension does not get activated. I use /etc/php5/conf.d/eaccelerator.ini.

I'm not sure what is wrong. Did something else change on PHP 5.5.9?

**Comment by NewEraCracker** [comment]
PHP 5.5 comes with a new caching extension (zend opcache). Please confirm that extension is not enabled in your environment.

**Comment by nebulorum** [comment]
I had to add a symbolic link to the /etc/php5/apache2/conf.d and remove the opcache. But now it's running. Thanks.

**Comment by NewEraCracker** [comment]
Thanks for the information. ;)
