### ISSUE TITLE
IS_CONSTANT_ARRAY -> IS_CONSTANT_AST

### ISSUE THREAD

**Issue by vGhost2000** [NewEraCracker/eaccelerator#4]
**php 5.6.14** win x84_64

```
ext\eaccelerator\ea_restore.c(143) : error C2065: IS_CONSTANT_ARRAY: необъявленный идентификатор
ext\eaccelerator\ea_restore.c(143) : error C2051: значение выражения для варианта выбора не является константой
ext\eaccelerator\ea_restore.c(462) : error C2065: IS_CONSTANT_ARRAY: необъявленный идентификатор
ext\eaccelerator\ea_restore.c(462) : error C2051: значение выражения для варианта выбора не является константой
```

https://github.com/php/php-src/blob/82ecdcdb6352f851e351f70f19b85aff06de0e4b/UPGRADING.INTERNALS

> l. Removal of IS_CONSTANT_ARRAY and IS_CONSTANT_INDEX hack
> 
>   These two #defines disappeared. Instead we have now IS_CONSTANT_AST which
>   covers also the functionality IS_CONSTANT_ARRAY bid and furthermore the
>   hack for marking zvals as constant index with IS_CONSTANT_INDEX is now
>   superfluous and so removed.
>   Please note that IS_CONSTANT_AST now has the same value than
>   IS_CONSTANT_ARRAY had.

**Comment by NewEraCracker** [comment]
Let me know if by replacing `IS_CONSTANT_ARRAY` with `IS_CONSTANT_AST` with text editor on those files works for building & using eAccelerator on PHP 5.6.

If so, I'll perform those changes on my repository.

**Comment by vGhost2000** [comment]
i just add line
#define IS_CONSTANT_ARRAY IS_CONSTANT_AST
in eaccelerator.h after #include "zend_extensions.h"
and all compile fine for me..

But i not tested yet.

**Comment by NewEraCracker** [comment]
Just an heads up as this change may not work at all.

From what I see Zend OPcache handle this very specifically for PHP 5.6:
http://lxr.php.net/xref/PHP_5_6/ext/opcache/zend_persist.c#177

I'll need help from someone, a good pull request, to add compatibility for PHP 5.6.
