### ISSUE TITLE
fnmatch.obj : error LNK2005: fnmatch already defined in fnmatch.obj

### ISSUE THREAD

**Issue by vGhost2000** [NewEraCracker/eaccelerator#5]
php 5.6.14 win x86_64 Microsoft Visual Studio 12.0

```
fnmatch.obj : error LNK2005: fnmatch уже определен в fnmatch.obj
libintl_a.lib(gettext.obj) : найден .netmodule MSIL или модуль, откомпилированный с параметром /GL; перезапускается компоновка с параметром /LTCG; добавьте /LTCG в командную строку компоновки для повы
шения производительности компоновщика
fnmatch.obj : error LNK2005: fnmatch уже определен в fnmatch.obj
   Создается библиотека x64\Release_TS\php5ts.lib и объект x64\Release_TS\php5ts.exp
x64\Release_TS\php5ts.dll : fatal error LNK1169: обнаружен многократно определенный символ - один или более
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.exe" : возвращенный код "0x2"
Stop.
```

**fnmatch.obj : error LNK2005: fnmatch already defined in fnmatch.obj**

**Comment by NewEraCracker** [comment]
You are most likely getting this error because you are trying to build eAcceleator statically into PHP which is not the recommended approach. You should build eAccelerator as a shared library instead.

Append `--enable-eaccelerator=shared` to the configuration command.

**Comment by vGhost2000** [comment]
Thanks, but unfortunately I need it static. Maybe better way just rename it to the needs of eAccelerator project?

**Comment by NewEraCracker** [comment]
As a trick. Edit the following:
- Line 48 of eaccelerator.c from `#  include "fnmatch.h"` to `#  include "win32/fnmatch.h"`
- Remove `fnmatch.c` from line 12 of config.w32

If if works, you're lucky. Otherwise I will not support this further, as I never needed to run eAccelerator statically on production.

**Comment by vGhost2000** [comment]
I just thought that there were made some changes to the standard procedure, becose i rename it. But if no, i better remove this files. Thanks for help.

Yes, it works :)
