### ISSUE TITLE
Makefile:199: recipe for target 'ea_restore.lo' failed

### ISSUE THREAD

**Issue by zer0soft** [NewEraCracker/eaccelerator#6]
I have debian 8.7 with PHP 5.6.29-0+deb8u1 trying to install your version of eaccelerator as the previous eA doesn't work. but after executing the make command i get that error.

**Comment by NewEraCracker** [comment]
PHP 5.6 has changed many things and there is no quick way to make eA compatible with it.

The last supported version is PHP 5.5.
